
#ifndef __CAPWAP_DTT_PROTOCOL_HEADER__
#define __CAPWAP_DTT_PROTOCOL_HEADER__

/*< 厂商标识*/
#define CW_VENDOR_ID	1567 //1567 Z-COM   5105 dtt

/***********************************************************************
 * Vendor specific payloads types for DTT
 * *********************************************************************/

/*Genetic element*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_GET_WTP_MAC							0x0001/*< AC获取WTP的MAC地址*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_GET_WTP_IPADDR						0x0002/*< AC获取WTP的IP地址*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_GET_WTP_NAME							0x0003/*< AC获取WTP的主机名*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_FILE_AC_IPADDR				0x0006/*< WTP获取文件所需AC的IP地址*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_GET_WTP_INFO							0x0009/*< AC获取WTP的信息（型号，隐藏版本号，fw名）*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_FILE_FILENAME				0x000c/*< WTP获取文件所需文件名*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_FILE_FTP_USER				0x000d/*< WTP获取文件所用FTP登陆用户名*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_FILE_FTP_PASSWD				0x000e/*< WTP获取文件所需FTP登陆密码 */
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_CONFIG_AC_IPADDR				0x0010/*< WTP获取Config文件所需AC的IP地址*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_CONFIG_FILENAME				0x0011/*< WTP获取Config文件的文件名*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_CONFIG_FTP_USER				0x0012/*< WTP获取Config文件所用FTP登录用户名*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_WTP_GET_CONFIG_FTP_PASSWD			0x0013/*< WTP获取Config文件所用FTP登录密码*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_INSERT_AUTH_CERTIFICATE				0x0014/*< 接入认证证书*/
#define 	CW_DTT_MSG_ELEMENT_GENETIC_DOUBLE_CARD_GET_WTP_ORTHER_MAC		0x0015/*< 双卡AP AC获取WTP的另一个MAC地址*/

/*Config element*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_MODE							0x0301/*< 无线模式*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_IS_DISABLED					0x0302/*< 启用/禁用RF*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_COUNTRY_CODE					0x0303/*< 国家代码 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_CHANNEL						0x0304/*< 信道 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_DATA_RATE					0x0305/*< 数据速率 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_BEACON_INTERVAL				0x0306/*< Beacon间隔时间 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_RTS_LIMITE					0x0307/*< RTS门限 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_DTIM_INTERVAL				0x0308/*< DTIM间隔时间 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_TX_POWER						0x0309/*< 发射功率 */

#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_INSERT_CONTROL_MODE			0x030b/*< 接入控制模式 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_KEY_TYPE					0x030d/*< WEP密钥类型 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_KEY_ONE					0x030e/*< WEP密钥1 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_KEY_TWO					0x030f/*< WEP密钥2 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_KEY_THREAD				0x0310/*< WEP密钥3 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_KEY_FOUR					0x0311/*< WEP密钥4 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_KEY_PASSPHRASE			0x0312/*< WEP密钥的Passphrase */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WPA_RE_AUTH_INTERVAL			0x0313/*< WPA重认证时间间隔 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WPA_KEY_UPDATE_CONDITION		0x0314/*< WPA密钥更新条件 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WPA_KEY_UPDATE_SECOND		0x0315/*< WPA密钥更新秒数 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WPA_KEY_UPDATE_PACKAGES		0x0316/*< WPA密钥更新包数 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_VAP_VLAN						0x0317/*< VAP的VLAN */

#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_VAP_SWITCH					0x0318/*< 启用/禁用VAP */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_SSID_NAME					0x0319/*< AP的SSID */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_SSID_HIDE					0x031a/*< 隐藏SSID */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_VAP_PROFILE					0x031b/*< VAP的Profile名称 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_VAP_WPA_PSK					0x031c/*< VAP的WPA-PSK */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_VAP_AUTH_TYPE				0x031d/*< VAP认证方式 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_VAP_PASSWD_TYPE				0x031e/*< VAP加密方式 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_WEP_DEFAULT_KEY				0x031f/*< 缺省的WEP密钥 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_ISOLATE_IS_DISABLED			0x0320/*< 启用/禁用无线端隔离 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_AUTO_CHANNEL					0x0321/*< 自动信道*/

#define 	CW_DTT_MSG_ELEMENT_CONFIG_MAC_INSERT_CONTROL					0x0322/*< MAC接入控制*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AP_WORK_MODE							0x0324/*< AP工作模式 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_REPEATER_REMOTE_AP1					0x032a/*< REPEATER_REMOTE_AP1 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_REPEATER_REMOTE_AP2					0x032b/*< REPEATER_REMOTE_AP2 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_REPEATER_REMOTE_AP3					0x032c/*< REPEATER_REMOTE_AP3 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_REPEATER_REMOTE_AP4					0x032d/*< REPEATER_REMOTE_AP4 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BURST_LENGTH							0x032e/*< 分片长度 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_LEAD_FRAME_LENGTH						0x032f/*< 前导帧类型 */

#define 	CW_DTT_MSG_ELEMENT_CONFIG_RADIUS_SERVER_IPADDR					0x0330/*< Radius Server 的IP地址 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_RADIUS_SERVER_PORT					0x0331/*< Radius Server 的端口 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_RADIUS_SERVER_KEY						0x0332/*< Radius Server 的密钥 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AUTO_CHANNEL_INTERVAL					0x0333/*< 自动信道间隔 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SIGNAL_RANK							0x0334/*< 信号等级\*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BALANCE_MODEL							0x0335/*< 均衡模 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BALANCE_GROUP							0x0336/*< 均衡组 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BALANCE_USERS							0x0337/*< 用户均衡 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BALANCE_FLUX							0x0338/*< 流量均衡 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_EXTEND_AUTH							0x0339/*< 扩展认证 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_DHCP_SNOOPING							0x033a/*< DHCP Snooping */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WTP_PASSWD							0x033b/*< WTP 密码 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_PROTECT_DOS_ATTACK					0x033c/*< 防范DOS攻击 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_REBOOT_WTP							0x033d/*< 重启WTP */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_USER_CONTROL_MODE						0x033e/*< 用户控制模式 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_MAX_CONNECT_USERS					0x033f/*< 根据用户数去设置连接的最大用户数 */

#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_MAX_THROUGHPUT_CAPACITY			0x0340/*< 根据流量去设置最大吞吐量 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_NTP_SWITCH								0x0341/*< 是否开启NTP */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_NTP_IPADDR							0x0342/*< NTP 的IP地址 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_LOAD_BALANCE_MAX_USERS				0x0343/*< 负载均衡最大用户数 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_LOAD_BALANCE_MAX_FLUX					0x0344/*< 负载均衡最大流量 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_MULTICAST_RATE						0x0345/*< 组播速率 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WMM									0x0346/*< WMM */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_MAX_VOIP_COUNT						0x0347/*< 最大的VoIP数量 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_NETWORK_CODING						0x0348/*< NETWORK_CODING*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AP_LOCATION							0x0349/*< AP_LOCATION */

#define 	CW_DTT_MSG_ELEMENT_CONFIG_WTP_NAME								0x0351/*< WTP 名称*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_LOAD_BALANCE_MAX_REFUSE_COUNT			0x0352/*< 负载均衡最大拒绝次数 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_VAP_MAX_STA_COUNT						0x0353/*< VAP最大终端数量 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_QOS_MAP								0x0354/*< QOS 映射*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_QOS_PRIORITY_MAP_1					0x0355/*< QOS优先级映射*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_QOS_PRIORITY_MAP_2					0x0356/*< QOS优先级映射*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_QOS_PRIORITY_MAP_3					0x0357/*< QOS优先级映射*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_QOS_PRIORITY_MAP_4					0x0358/*< QOS优先级映射*/

#define 	CW_DTT_MSG_ELEMENT_CONFIG_LOCATION_TRANSMIT						0x0359/*< 本地转发*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WAPI_PSK_KEY							0x0365/*< WAPI PSK 密钥*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AUTO_POWER							0x0369/*< 自动功率 */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WTP_HOSTNAME							0x0371/*< WTP的主机名*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BASE_SSID_BANDWIDTH_CONTROL			0x0372/*< 基于SSID的带宽控制*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BASE_SSID_UP_BANDWIDTH_CONTROL		0x0373/*< 基于SSID的上行带宽控制*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_BASE_SSID_DOWN_BANDWIDTH_CONTROL		0x0374/*< 基于SSID的下行带宽控制*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_CHANNEL_MODE					0x0375/*< 信道模式 (11n only)*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_HIGH_FLOW_PROTECT			0x0376/*< 高流量保护*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_SPECIAL_STREAM_COUNT			0x0377/*< 空间流个数*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_AMPDU_FRAME_AGGREGATION		0x0378/*< AMPDU帧聚合*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_AMSDU_FRAME_AGGREGATION		0x0379/*< AMSDU帧聚合*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_SHORT_GI_PROTECT				0x037a/*< Short-GI保护区间*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_RIFS_LEAN_FRAME				0x037b/*< RIFS精简讯框*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_11N_ONLY_CHANNEL_PROTECT				0x037c
#define 	CW_DTT_MSG_ELEMENT_CONFIG_IGMP_SNOOPING_SWITCH					0x037d/*< IGMP Snooping开关*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AUTO_RATE_CHAGE_MODE					0x037e/*< 自动频率变更模式*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_IGMP_AGENCY_MODE						0x037f/*< IGMP代理模式*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_MTU_VALUE								0x0382/*< 网络侧接口MTU值*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SSID_PRIORITY							0x0391/*< SSID优先级*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIDS_CONFIG							0x0392/*< WIDS配置*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_TAPTRAP_PRIORITY						0x0393/*< TAPTRAP设置*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SSID_COUNT							0x0394/*< SSID个数设置*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_TAP_UPGRADE_FTP_IPADDR				0x0395/*< TAP升级FTP地址*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_TAP_UPGRADE_TYPE						0x0396/*< TAP升级类型*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIDS_SPOOFING_SWITCH					0x0397/*< WIDS-SPOOFING开关*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIDS_MODE_CHOOSE						0x0398/*< WIDS模式选择*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIDS_FLOOD_SWITCH						0x0399/*< WIDS泛洪开关*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AC_WAN_STATE							0x039a/*< AC的WAN口状态*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_IS_ALLOW_11N_STA_CONNECT				0x039b/*< 是否允许11n终端接入*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AP_REAL_COLLECT_SWITCH				0x039c/*< AP实时采集开关*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AP_REAL_COLLECT_CYCLE					0x039d/*< AP实时采集周期*/

#define 	CW_DTT_MSG_ELEMENT_CONFIG_BASE_MAC_BANDWIDTH_CONTROL_DEFAULT	0x03af/*< 基于MAC的带宽控制的缺省带宽*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AP_ASK_AC_AUTH_MACADDR				0x03f9/*< AP请求AC对该MAC地址认证*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_AP_ASK_AC_AUTH_MACADDR_AC_RESPOSE		0x03fa/*< AC将MAC地址认证结果发给AP*/

#define 	CW_DTT_MSG_ELEMENT_CONFIG_WTP_UPGRADE_FIRMWARE					0x0401/*< WTP升级FirmWare */
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WTP_UPDATE_CONFIGFILE					0x0402/*< WTP更新配置文件*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_WTP_DOWNLOAD_WAPI_CERTIFICATE			0x0403/*< WTP下载WAPI证书*/

#define 	CW_DTT_MSG_ELEMENT_CONFIG_LINK_INTACT_CHECK						0x0600/*< 链路完整性检测*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_RESET_FACTORY_SETTING					0x0601/*< 恢复出厂信息*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_FORMWORK_NUM						0x0602/*< 设置模版编号*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_PROJECT_STATE						0x0603/*< 设置工程状态*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_DATA_CHANNEL_IPADDR				0x0604/*< 设置数据通道IP地址*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_PERFORMANCE_DATE_STAT_DURATION	0x0605/*< 设置性能数据统计时长*/
#define 	CW_DTT_MSG_ELEMENT_CONFIG_SET_PERFORMANCE_DATE_SAMPLE_DURATION	0x0606/*< 设置性能数据抽样时长*/

#define 	CW_DTT_MSG_ELEMENT_CONFIG_WIRELESS_BANDWIDTH_CONTROL_MODE		0x0650/*< 无线带宽控制模式*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_VLAN_BANDWIDTH_CONTROL_LIST			0x0651/*< vlan带宽控制列表*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_TAP_FLUX_CONTROL_STA_LIST				0x0652/*< TAP流量控制STA表*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_WAPI_AUTH_AS_IPADDR					0x0653/*< WAPI认证时AS的IP地址*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_WAPI_AUTH_CERTIFICATE_TYPE			0x0654/*< WAPI认证的证书类型*/

#define		CW_DTT_MSG_ELEMENT_CONFIG_AP_SOFTWARE_VERSION					0x0660/*< AP的软件版本号*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_RADIUS_USER_BANDWIDTH_CONTROL_PARAM	0x0661/*< Radius用户带宽控制参数*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SUPPORT_REDIUSSERVER_DM_MSG			0x0662/*< 支持radiusServer的DM消息*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_USER_IDLE_AUTH_TIME_AND_FLUX_SWITCH	0x0663/*< 设置用户闲置重认证时间闲置重认证流量的开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_USER_IDLE_AUTH_TIME				0x0664/*< 设置用户闲置重认证时间*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_USER_IDLE_AUTH_FLUX				0x0665/*< 设置用户闲置重认证流量*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_NASID								0x0666/*< 设置NASID*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_AUTH_RENEW_INTERVAL				0x0667/*< 设置EAP-SIM/PEAP认证续费间隔时间*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_ALARM_RETRY_WAITTIME				0x0668/*< 设置告警重发等待时间*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_WTP_USER_NAME							0x0669/*< WTP 用户名*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_AP_RATE_CROWD						0x066a/*< 设置AP速率集*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_QOS_PARAM							0x066b/*< 设置QOS参数*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_WAPI_CONFIG_AND_CAPABILITY		0x066c/*< 设置WAPI配置与性能参数*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_QOS_CONFIG_AND_CAPABILITY			0x066d/*< 设置QOS配置与性能参数*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_PACKAGE_CAPTURE_SWITCH				0x066e/*< 报文捕获开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_AP_EACH_PACKAGE_POEWER_CONFIG_SWITCH	0x066f/*< AP逐包功率配置开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_PING_TEST_SWITCH						0x0670/*< ping test开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_PING_IPADDR							0x0671/*< ping IPaddr*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_DEVICE_IPADDR_GET_TYPE				0x0672/*< 设备的IP地址获得方式*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_ARP_PACKAGE_LIMIT_VALUE				0x0673/*< ARP报文限速阈值*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_WIDS_SCAN_INTERVAL					0x0674/*< WIDS扫描间隔*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_RTT_CHECK_SWITCH						0x0675/*< RTT检测开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_RTT_CHECK								0x0676/*< RTT检测*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_OPEN_80211N							0x0677/*< 开启802.11n*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_FLOOD_ATTACK_CHECK_SWITCH				0x0678/*< 泛洪攻击检测开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SPOOF_ATTACK_CHECK_SWITCH				0x0679/*< Spoof攻击检测开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_WEAK_IV_CHECK_SWITCH					0x067a/*< Weak IV检测开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_MLD_SNOOP_SWITCH						0x067b/*< MLD snooping开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_UNCONNECT_IS_CLOSE_SSID				0x067c/*< 设置AP与AC间的隧道中断是否自动关闭SSID开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_FORCE_RATE							0x067d/*< 强制速率*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SUPPORT_RATE							0x067e/*< 支持速率*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_NEED_ACL_AUTH_SSID					0x067f/*< 需要ACL鉴权的SSID*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_COA_DYNAMIC_BANDWIDTH_CONTROL_PARAM	0x0680/*< 基于coa协议的动态radius带宽控制参数*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_NEED_ACL_AUTH_VALN					0x0681/*< 需要做ACL鉴权的VALN*/

#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_WTP_TIME_ZONE						0x0682/*< 设置WTP时区*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_WTP_TIME							0x0683/*< 设置WTP时间*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_NTP_SERVER_PORT					0x0684/*< 设置NTP server端口*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_EACH_VAP_USER_AUTH_TYPE			0x0685/*< 设置各VAP用户认证方式*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_STA_VLAN_ISOLATION_SWITCH			0x0686/*< 设置无线终端VLAN间隔离开关*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_AP_REPORT_LOG_INTERVAL			0x0687/*< 设置AP的上报格式化日志的间隔*/
#define		CW_DTT_MSG_ELEMENT_CONFIG_SET_FISH_AP_LIST						0x0688/*< 设置钓鱼AP列表*/

/*Report element*/
#define		CW_DTT_MSG_ELEMENT_REPORT_WTP_UPGRATE_FIRMWARE_SUCCESS			0x0501/*< WTP升级FirmWare成功*/
#define		CW_DTT_MSG_ELEMENT_REPORT_FIT_AP_INFO							0x0502/*< 瘦AP信息上报*/
#define		CW_DTT_MSG_ELEMENT_REPORT_STATION_INFO							0x0503/*< 终端信息上报*/
#define		CW_DTT_MSG_ELEMENT_REPORT_UNSAFE_AP_INFO						0x0504/*< 非法AP信息上报*/
#define		CW_DTT_MSG_ELEMENT_REPORT_BLACK_LIST							0x0505/*< 黑名单上报*/
#define		CW_DTT_MSG_ELEMENT_REPORT_UNSAFE_STA_INFO						0x0506/*< 非法终端信息上报*/
#define		CW_DTT_MSG_ELEMENT_REPORT_FIT_AP_INFO_NEW						0xa502/*< 瘦AP信息上报(新)*/
#define		CW_DTT_MSG_ELEMENT_REPORT_STATION_INFO_NEW						0xa503/*< 终端信息上报(新)*/


#define 	WTP_ACL_TRAP_STA_ONLINE											0x1153/*< ACL trap station online*/

#endif

