#!/bin/sh
#for check and set led

#led: off , red, red_blink, blue, blue_blink, green, green_blink

#network 0/1/2 0正常 1没有ip或网络不通 闪红灯 2ac异常 亮红灯
#uwb     0/1/2 0正常 （1模块未启用  2模块数据异常）亮绿灯 3硬件接口异常 闪绿灯
#blue    0/1/2 0正常 （1模块未启用  2模块数据异常）亮蓝灯 3硬件接口异常 闪蓝灯
#全部正常 灯不亮

AC_NETWORK="/tmp/ac/status/network"
UWB="/tmp/ac/status/uwb"
BLUE="/tmp/ac/status/blue"

led_status=""
blink_status=""
last_status=""

#set led red green blue off

set_led_off()
{
	echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
	echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/brightness
	echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness
}

set_red_led()
{
    if [ "$led_status" != "red" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/brightness
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness
        led_status=red
    fi

    if [ "$1" == "1" ] && [ "$blink_status" != "red_blink" ];then
        echo "timer" > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/trigger
        blink_status=red_blink
    elif [ "$1" == "0" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
        echo 1 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
        blink_status=red
    fi
 
}

set_blue_led()
{
    if [ "$led_status" != "blue" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/brightness
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
        led_status=blue
    fi
    
    if [ "$1" == "1" ] && [ "$blink_status" != "blue_blink" ];then
        echo "timer" > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/trigger
        blink_status=blue_blink
    elif [ "$1" == "0" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness
        echo 1 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness
        blink_status=blue
    fi
}

set_green_led()
{
    if [ "$led_status" != "green" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness
        led_status=green
    fi

    if [ "$1" == "1" ] && [ "$blink_status" != "green_blink" ];then
        echo "timer" > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/trigger
        blink_status=green_blink
    elif [ "$1" == "0" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/brightness
        echo 1 > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/brightness
        blink_status=green
    fi
}

set_rb_led()
{
    if [ "$led_status" != "rb" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:green:5g/brightness
        led_status=rb
    fi 
    
    if [ "$1" == "1" ] && [ "$blink_status" != "rb_blink" ];then
        echo "timer" > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/trigger
        echo "timer" > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/trigger
        blink_status=rb_blink
    elif [ "$1" == "0" ];then
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
        echo 0 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness
       
        echo 1 > /sys/devices/platform/leds-gpio/leds/airocov:red:sys/brightness
        echo 1 > /sys/devices/platform/leds-gpio/leds/airocov:blue:2g/brightness

        blink_status=rb
    fi   
}

#check network
check_network()
{
	local route=""
	route=$(ubus call network.interface.lan status | grep nexthop | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
	if [ "$route" != "" ];then
		if  ping -c1 -W1 $route >/dev/null 2>&1 ; then
		    echo 1 
		else   
			echo 0 
		fi
	else
		echo 0
	fi
}

#set led status
check_led_status()
{
    #check status
    ac_status=$(cat $AC_NETWORK 2>/dev/null)
    uwb_status=$(cat $UWB 2>/dev/null)
    blue_status=$(cat $BLUE 2>/dev/null)

    if [ "$(uci get blconfig.con.disabled)" == 1 ];then
        blue_status=0
    fi

    if [ "$(uci get uwbcon.con.disabled)" == 1 ];then
        uwb_status=0
    fi

    #echo ac $ac_status
    #echo uwb $uwb_status
    #echo blue $blue_status

	#set led status
	if [ "$(check_network)" == "0" ] || [ "$ac_status" == "1" ];then
    	if [ "$last_status" != "ac1" ];then
    		set_rb_led 1;
    		last_status="ac1"; 
    	fi
    	return 0;
    elif [ "$ac_status" == "2" ] || [ "$ac_status" == "" ];then
    	if [ "$last_status" != "ac2" ];then
    		set_rb_led 0;
    		last_status="ac2"; 
    	fi
    	return 0;
    elif [ "$uwb_status" == "1" ] || [ "$uwb_status" == "2" ];then
    	if [ "$last_status" != "uwb2" ];then
    		set_green_led 0;
    		last_status="uwb2"; 
    	fi
    	return 0;
    elif [ "$uwb_status" == "3" ];then
    	if [ "$last_status" != "uwb3" ];then
    		set_green_led 1;
    		last_status="uwb3"; 
    	fi
    	return 0;
    elif [ "$blue_status" == "1" ] || [ "$blue_status" == "2" ];then
    	if [ "$last_status" != "blue2" ];then
    		set_blue_led 0;
    		last_status="blue2"; 
    	fi
    	return 0;
    elif [ "$blue_status" == "3" ];then
    	if [ "$last_status" != "blue3" ];then
    		set_blue_led 1;
    		last_status="blue3"; 
    	fi
    	return 0;
    else
    ###status is ok
    ###if [ "$ac_status" == "0" ] && [ "$uwb_status" == "0" ] && [ "$blue_status" == "0" ];then
    	if [ "$last_status" != "ok" ];then
    		set_led_off;
    		last_status="ok"; 
    	fi
    fi

}

set_default_led()
{
    set_red_led 0;
    sleep 1;

    set_blue_led 0;
    sleep 1;

    set_green_led 0;
    sleep 1;

    set_led_off;

    led_status=default
}


#led init
set_default_led;

#start led check
while true;
do
    check_led_status;
    sleep 5;
done


