#!/bin/sh

#set mesh batman default config 

#wireless mesh
uci batch <<-EOF
	set wireless.wmesh.network='mesh'
	set wireless.wmesh.mesh_fwding='0'
	set wireless.wmesh.disassoc_low_ack='1'
	
	commit wireless
EOF

#interface
uci batch <<-EOF
	set network.lan.ifname='eth0.1 eth0.2 bat0'
	set network.lan.proto='dhcp'
	del network.lan.ipaddr
	del network.lan.netmask
	del network.lan.ip6assign

	del network.wan
	del network.wan6

	set network.mesh=interface
	set network.mesh.proto='batadv_hardif'
	set network.mesh.master='bat0'
	set network.mesh.mtu='1536'
	set network.mesh.ifname='wlan_mesh'

	set network.bat0=interface
	set network.bat0.proto='batadv'
	set network.bat0.routing_algo='BATMAN_IV'
	set network.bat0.aggregated_ogms='1'
	set network.bat0.ap_isolation='1'
	set network.bat0.bonding='0'
	set network.bat0.fragmentation='1'
	set network.bat0.gw_mode='off'
	set network.bat0.log_level='0'
	set network.bat0.orig_interval='1000'
	set network.bat0.bridge_loop_avoidance='1'
	set network.bat0.distributed_arp_table='1'
	set network.bat0.multicast_mode='1'
	set network.bat0.multicast_fanout='16'
	set network.bat0.network_coding='0'
	set network.bat0.hop_penalty='30'
	set network.bat0.isolation_mark='0x00000000/0x00000000'

	del dhcp.lan
	del dhcp.wan
	del dhcp.odhcpd
	
	commit network
	commit dhcp
EOF

	/etc/init.d/network reload
	/etc/init.d/dnsmasq
	wifi
	
	
exit 0

