#!/bin/sh /etc/rc.common

# Copyright (C) 2016 datang.com

START=99
STOP=10

CARD=`cat /usr/capwap/config.wtp  | grep AP_CARD_COUNT | cut -d " " -f 2`

#set fit/fat apmode
/usr/capwap/fit_fat.sh

#insmod qos modules
#insmod /lib/modules/3.3.8/cls*.ko
#insmod /lib/modules/3.3.8/sch*.ko


start() {
	if [ `uci get wtp.cfg.enable` -eq 0 ];then
        exit
    fi
    
    if [ -d "/tmp/capwap" ];then
	    echo "/tmp/capwap exist"
	else
	    mkdir -p /tmp/capwap
	fi

    if [ "$(lsmod | grep cloud_wlan)" == "" ];then
        insmod $(find /lib -name cloud_wlan.ko)
		#renew dhcp for capwap 43 option
		#ifup lan
    fi

	pid=`pgrep WTP`
	if [ -z "$pid" ];then
    	cd /usr/capwap
		./WTP ./ &
	fi
}

stop() {
	pid=`pgrep WTP`
	if [ ! -z "$pid" ]; then
		kill -9 $pid
	fi
}

restart() {
	stop
	start
}
