#!/bin/sh /etc/rc.common
START=10

boot()
{
	MTD_NAME=$(cat /proc/mtd | grep art | awk -F: '{print $1}')
	MAC=$(hexdump -C -n 6 /dev/$MTD_NAME | awk 'NR==1{print $5$6$7}' | tr a-z A-Z)

	uci batch <<-EOF
		set system.@system[0].hostname=Mesh-$MAC
		commit system
	EOF
	echo Mesh-$MAC > /proc/sys/kernel/hostname
}

