/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: datatype.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "datatype.h"
void student__init(Student *message)
{
    static Student init_value = STUDENT__INIT;
    *message                  = init_value;
}
size_t student__get_packed_size(const Student *message)
{
    assert(message->base.descriptor == &student__descriptor);
    return protobuf_c_message_get_packed_size(( const ProtobufCMessage * )(message));
}
size_t student__pack(const Student *message, uint8_t *out)
{
    assert(message->base.descriptor == &student__descriptor);
    return protobuf_c_message_pack(( const ProtobufCMessage * )message, out);
}
size_t student__pack_to_buffer(const Student *message, ProtobufCBuffer *buffer)
{
    assert(message->base.descriptor == &student__descriptor);
    return protobuf_c_message_pack_to_buffer(( const ProtobufCMessage * )message, buffer);
}
Student *student__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
    return ( Student * )protobuf_c_message_unpack(&student__descriptor, allocator, len, data);
}
void student__free_unpacked(Student *message, ProtobufCAllocator *allocator)
{
    assert(message->base.descriptor == &student__descriptor);
    protobuf_c_message_free_unpacked(( ProtobufCMessage * )message, allocator);
}
void school__init(School *message)
{
    static School init_value = SCHOOL__INIT;
    *message                 = init_value;
}
size_t school__get_packed_size(const School *message)
{
    assert(message->base.descriptor == &school__descriptor);
    return protobuf_c_message_get_packed_size(( const ProtobufCMessage * )(message));
}
size_t school__pack(const School *message, uint8_t *out)
{
    assert(message->base.descriptor == &school__descriptor);
    return protobuf_c_message_pack(( const ProtobufCMessage * )message, out);
}
size_t school__pack_to_buffer(const School *message, ProtobufCBuffer *buffer)
{
    assert(message->base.descriptor == &school__descriptor);
    return protobuf_c_message_pack_to_buffer(( const ProtobufCMessage * )message, buffer);
}
School *school__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
{
    return ( School * )protobuf_c_message_unpack(&school__descriptor, allocator, len, data);
}
void school__free_unpacked(School *message, ProtobufCAllocator *allocator)
{
    assert(message->base.descriptor == &school__descriptor);
    protobuf_c_message_free_unpacked(( ProtobufCMessage * )message, allocator);
}
static const ProtobufCFieldDescriptor student__field_descriptors[3] = {
    {
        "id", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
        offsetof(Student, id), NULL, NULL, 0,                          /* flags */
        0, NULL, NULL                                                  /* reserved1,reserved2, etc */
    },
    {
        "name", 2, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_STRING, 0, /* quantifier_offset */
        offsetof(Student, name), NULL, NULL, 0,                          /* flags */
        0, NULL, NULL                                                    /* reserved1,reserved2, etc */
    },
    {
        "age", 3, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_INT32, 0, /* quantifier_offset */
        offsetof(Student, age), NULL, NULL, 0,                         /* flags */
        0, NULL, NULL                                                  /* reserved1,reserved2, etc */
    },
};
static const unsigned student__field_indices_by_name[] = {
    2, /* field[2] = age */
    0, /* field[0] = id */
    1, /* field[1] = name */
};
static const ProtobufCIntRange   student__number_ranges[1 + 1] = {{1, 0}, {0, 3}};
const ProtobufCMessageDescriptor student__descriptor           = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "Student",
    "Student",
    "Student",
    "",
    sizeof(Student),
    3,
    student__field_descriptors,
    student__field_indices_by_name,
    1,
    student__number_ranges,
    ( ProtobufCMessageInit )student__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const Grade                    school__grade__default_value = GRADE__SENIOR;
static const ProtobufCFieldDescriptor school__field_descriptors[2] = {
    {
        "grade", 1, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_TYPE_ENUM, offsetof(School, has_grade),
        offsetof(School, grade), &grade__descriptor, &school__grade__default_value, 0, /* flags */
        0, NULL, NULL                                                                  /* reserved1,reserved2, etc */
    },
    {
        "student", 2, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_MESSAGE, 0, /* quantifier_offset */
        offsetof(School, student), &student__descriptor, NULL, 0,            /* flags */
        0, NULL, NULL                                                        /* reserved1,reserved2, etc */
    },
};
static const unsigned school__field_indices_by_name[] = {
    0, /* field[0] = grade */
    1, /* field[1] = student */
};
static const ProtobufCIntRange   school__number_ranges[1 + 1] = {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor school__descriptor           = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "School",
    "School",
    "School",
    "",
    sizeof(School),
    2,
    school__field_descriptors,
    school__field_indices_by_name,
    1,
    school__number_ranges,
    ( ProtobufCMessageInit )school__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCEnumValue grade__enum_values_by_number[4] = {
    {"PRIMARY", "GRADE__PRIMARY", 0},
    {"JUNIOR", "GRADE__JUNIOR", 1},
    {"SENIOR", "GRADE__SENIOR", 2},
    {"COLLEGE", "GRADE__COLLEGE", 3},
};
static const ProtobufCIntRange       grade__value_ranges[]         = {{0, 0}, {0, 4}};
static const ProtobufCEnumValueIndex grade__enum_values_by_name[4] = {
    {"COLLEGE", 3},
    {"JUNIOR", 1},
    {"PRIMARY", 0},
    {"SENIOR", 2},
};
const ProtobufCEnumDescriptor grade__descriptor = {
    PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
    "Grade",
    "Grade",
    "Grade",
    "",
    4,
    grade__enum_values_by_number,
    4,
    grade__enum_values_by_name,
    1,
    grade__value_ranges,
    NULL,
    NULL,
    NULL,
    NULL /* reserved[1234] */
};
